//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebKassa.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ENERGO_GREntities : DbContext
    {
        public ENERGO_GREntities()
            : base("name=ENERGO_GREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PAS_RREGION> PAS_RREGION { get; set; }
        public virtual DbSet<PAS_RSTREET> PAS_RSTREET { get; set; }
        public virtual DbSet<PAS_RTOWN> PAS_RTOWN { get; set; }
        public virtual DbSet<VW_BUILDINGS> VW_BUILDINGS { get; set; }
        public virtual DbSet<RSTREETS> RSTREETS { get; set; }
        public virtual DbSet<V_ABONS> V_ABONS { get; set; }
        public virtual DbSet<DOGOVORS> DOGOVORS { get; set; }
    }
}
