//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebKassa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAS_RTOWN
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string TOWN_TYPE { get; set; }
        public Nullable<int> TOWN_TYPE_ID { get; set; }
        public string CODECALL { get; set; }
        public string CODECALLADD { get; set; }
        public string REFSERVICE { get; set; }
        public int CODE { get; set; }
        public short LOCAL { get; set; }
        public short VILLAGE { get; set; }
        public Nullable<int> CREATEUSERID { get; set; }
        public System.DateTime CREATEDATE { get; set; }
        public Nullable<int> MODIFYUSERID { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public Nullable<int> TOWN_AREA { get; set; }
        public string FULL_NAME { get; set; }
        public Nullable<int> REGION_ID { get; set; }
        public string PL_ID { get; set; }
        public string FIAS_CODE { get; set; }
    }
}
