//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebKassa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAS_RREGION
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public System.DateTime CREATEDATE { get; set; }
        public Nullable<int> CREATEUSERID { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public Nullable<int> MODIFYUSERID { get; set; }
        public Nullable<int> PROVINCE_ID { get; set; }
        public Nullable<int> LOCAL { get; set; }
        public Nullable<int> SHOW_GRP_LIST { get; set; }
        public string NAME2 { get; set; }
        public string RO { get; set; }
        public string FIAS_CODE { get; set; }
    }
}
