//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebKassa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSTREETS
    {
        public int ID { get; set; }
        public string STREET { get; set; }
        public int CODE { get; set; }
        public int TOWN_ID { get; set; }
        public System.DateTime CREATEDATE { get; set; }
        public Nullable<int> CREATEUSERID { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public Nullable<int> MODIFYUSERID { get; set; }
        public Nullable<int> CONTR { get; set; }
        public string FIAS_CODE { get; set; }
    }
}
