//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebKassa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ABONS
    {
        public Nullable<System.DateTime> BIRTHDATE { get; set; }
        public int ID { get; set; }
        public string G_LICSCHET { get; set; }
        public string UETS_LIC { get; set; }
        public string TOWN { get; set; }
        public string STREET { get; set; }
        public string HOUSE { get; set; }
        public string CORPS { get; set; }
        public Nullable<int> APPARTS { get; set; }
        public string LETTER { get; set; }
        public string NAME { get; set; }
        public string ZKX_NAME { get; set; }
        public string PHONE { get; set; }
        public Nullable<decimal> BALANCE { get; set; }
        public string NOTE { get; set; }
        public Nullable<int> REGION_ID { get; set; }
        public Nullable<int> TOWN_ID { get; set; }
        public Nullable<int> TOWN_AREA_ID { get; set; }
        public Nullable<int> STREET_ID { get; set; }
        public Nullable<int> CLIENT_ID { get; set; }
        public Nullable<int> ZKX_ID { get; set; }
        public Nullable<int> ZKX_ORGCODE { get; set; }
        public short IS_ACTIVE { get; set; }
        public string NLS { get; set; }
        public Nullable<int> SUPER_ABONENT { get; set; }
        public int BUILDING_ID { get; set; }
        public Nullable<decimal> OCC_FULLSPACE { get; set; }
        public Nullable<int> ROOMS { get; set; }
        public Nullable<int> REALTYTYPE { get; set; }
        public Nullable<int> GIS_EXPORT { get; set; }
        public string ADDRESS { get; set; }
        public string TOWN_FULL { get; set; }
        public string GIS_ID { get; set; }
        public string GIS_CODE { get; set; }
        public string COD_FIAS { get; set; }
        public Nullable<int> TYPE_LS { get; set; }
        public Nullable<int> STATUS_AP { get; set; }
        public Nullable<int> TYPE_OSNOV { get; set; }
    }
}
