//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebKassa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_BUILDINGS
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> STREET_ID { get; set; }
        public string HOUSE { get; set; }
        public string CORPS { get; set; }
        public string REGNUM { get; set; }
        public Nullable<int> OWNER_ID { get; set; }
        public Nullable<int> OWNERSHIPTYPE_ID { get; set; }
        public Nullable<decimal> MAINTKOEF { get; set; }
        public Nullable<int> ZKX_ID { get; set; }
        public Nullable<System.DateTime> BUILDDATE { get; set; }
        public Nullable<System.DateTime> DATA_R { get; set; }
        public Nullable<int> DETERIOR { get; set; }
        public Nullable<int> MATERIAL { get; set; }
        public System.DateTime CREATEDATE { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public Nullable<decimal> HEIGHT { get; set; }
        public Nullable<int> GEU { get; set; }
        public Nullable<short> LIFT { get; set; }
        public Nullable<short> LIFT_H { get; set; }
        public Nullable<short> C_HV { get; set; }
        public Nullable<short> C_GV { get; set; }
        public Nullable<short> C_BATH { get; set; }
        public Nullable<short> C_TIP { get; set; }
        public Nullable<short> C_GR { get; set; }
        public Nullable<short> C_OTOP { get; set; }
        public Nullable<short> C_TBO { get; set; }
        public Nullable<short> C_MU { get; set; }
        public Nullable<short> C_PPA { get; set; }
        public Nullable<int> MODIFYUSERID { get; set; }
        public Nullable<int> CREATEUSERID { get; set; }
        public Nullable<short> ETAZH { get; set; }
        public Nullable<short> IS_PASSPORT { get; set; }
        public string PLAN_PATH { get; set; }
        public Nullable<short> C_GAZ { get; set; }
        public Nullable<short> C_CANAL { get; set; }
        public Nullable<int> ACCOMP { get; set; }
        public Nullable<int> ACCOMP2 { get; set; }
        public short BUILDNAME { get; set; }
        public Nullable<int> DOORCOUNT { get; set; }
        public string NUM { get; set; }
    }
}
